name: Regression Tests

on:
  push:
    branches:
      - master
      - 'stable/**'
      - bus_monitor_impr
  pull_request:
    branches:
      - master
      - 'stable/**'

jobs:
  tests:
    runs-on: ubuntu-22.04
    needs: lint_job  # Depends on lint job from lint.yaml
    id: regression_job

    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Icarus and its requirements
        run: |
          sudo apt update
          sudo apt-get install build-essential libboost-dev iverilog verilator
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: pip install --upgrade nox

      - name: Run nox tests
        run: nox -s "run-${{ matrix.python-version }}"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
