name: Tests

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'

jobs:
  regresion-tests:
    name: Regresion Tests
    runs-on: ubuntu-latest
    container: aignacio/rtldev:latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install testing requirements
      run: |
        pip install nox
    - name: Run tests
      run: |
        nox -s run-3.10
